# Generated by Django 5.2.7 on 2025-10-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_profile_age_alter_profile_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='CatProfile',
        ),
    ]
